import {
  FaArrowRight,
  FaArrowTrendUp,
  FaBars,
  FaBed,
  FaCalendarCheck,
  FaCalendarDays,
  FaChartLine,
  FaCloudArrowUp,
  FaDollarSign,
  FaEnvelope,
  FaEye,
  FaEyeSlash,
  FaFire,
  FaHouse,
  FaInstagram,
  FaLeaf,
  FaLinkedinIn,
  FaListCheck,
  FaLock,
  FaMapLocationDot,
  FaPaperPlane,
  FaPen,
  FaShieldHalved,
  FaStar,
  FaTree,
  FaUmbrellaBeach,
  FaUsers,
  FaWifi,
  FaXmark,
  FaGem,
  FaKitchenSet,
  FaCar,
  FaBath,
  FaTwitter,
  FaHouseChimney,
  FaHotTubPerson,
  FaPaw,
  FaHeart,
  FaRegCommentDots,
  FaMobileScreenButton,
  FaMagnifyingGlass,
  FaDownload,
} from 'react-icons/fa6';

const ICON_MAP = {
  'arrow-right': FaArrowRight,
  trend: FaArrowTrendUp,
  bars: FaBars,
  bed: FaBed,
  bath: FaBath,
  calendar: FaCalendarDays,
  'calendar-check': FaCalendarCheck,
  chart: FaChartLine,
  upload: FaCloudArrowUp,
  dollar: FaDollarSign,
  email: FaEnvelope,
  eye: FaEye,
  'eye-off': FaEyeSlash,
  fire: FaFire,
  house: FaHouse,
  instagram: FaInstagram,
  leaf: FaLeaf,
  linkedin: FaLinkedinIn,
  'list-check': FaListCheck,
  lock: FaLock,
  location: FaMapLocationDot,
  send: FaPaperPlane,
  pen: FaPen,
  shield: FaShieldHalved,
  sofa: FaHouse,
  star: FaStar,
  tree: FaTree,
  umbrella: FaUmbrellaBeach,
  users: FaUsers,
  wifi: FaWifi,
  close: FaXmark,
  gem: FaGem,
  kitchen: FaKitchenSet,
  parking: FaCar,
  twitter: FaTwitter,
  home: FaHouseChimney,
  hotub: FaHotTubPerson,
  paw: FaPaw,
  heart: FaHeart,
  comment: FaRegCommentDots,
  mobile: FaMobileScreenButton,
  search: FaMagnifyingGlass,
  download: FaDownload,
};

export function Icon({ name, className = '', ...props }) {
  const Component = ICON_MAP[name];

  if (!Component) {
    return null;
  }

  return <Component className={className} aria-hidden="true" {...props} />;
}
